Repository antares-sql/antares, pull requests merged in 2025-01, with the labels that each got.

#912 Update WorkspaceExploreBarSchema.vue - Changed search to not be case sensitive
  .all-contributorsrc
  README.md
  src/renderer/components/WorkspaceExploreBarSchema.vue
Labels: enhancement 🚀

#920 fix: Cannot update column value with composite primary key and JSON column #916
  src/common/libs/sqlUtils.ts
  src/main/ipc-handlers/tables.ts
Labels: bug 🪲

#922 Update localization
  .all-contributorsrc
  README.md
  src/renderer/i18n/zh-CN.ts
Labels: translation 🌍

#921 Zoom in/out and fullscreen shortcuts
  src/common/shortcuts.ts
  src/main/libs/ShortcutRegister.ts
  src/renderer/components/ModalSettingsShortcuts.vue
  src/renderer/components/WorkspaceTabQueryEmptyState.vue
  src/renderer/i18n/en-US.ts
Labels: enhancement 🚀
